### ISSUE TITLE
linking to supabase

### ISSUE THREAD

**Issue by astanley86** [KolbySisk/next-supabase-stripe-starter#2]
I'm super excited about this repo!  I'm new to Vercel, Supabase and Resend.  On a brand new project, I'm following the instructions for this project through the README and it appears that everything ran successfully and I'm able to run `npm run dev` 

However going to the Pricing Page, visual studio code terminal shows:

`Could not find a relationship between 'products' and 'prices' in the schema cache`

![image](https://github.com/KolbySisk/next-supabase-stripe-starter/assets/3408081/45cfcc20-813e-4408-913e-06c0e588ff98)

I did notice that at the `npm run supabase:link` step I get this:
`Local config differs from linked project. Try updating supabase\config.toml`

Is that my problem?  What am I missing?

**Comment by astanley86** [comment]
Oh wait a minute!  I think I know what's going on at least with the schema issue.  I had deleted the "supabase" directory at one point trying to resolve the config.toml situation and that meant I removed the "migrations" folder as well so reverting back to the git clone included the missing file `20240115041359_init.sql`  and running `npm run migration:up` actually created what was missing in my db

**Comment by astanley86** [comment]
I got it to work!  I think the docs could be improved by explaining the step is necessary to re-deploy to vercel once you have the local code running because before I did a `git push` my stripe webhooks were failing.  Now I re-ran the stripe fixtures and that synced things back into my db

**Comment by KolbySisk** [comment]
Happy you got it working @astanley86 . I'll work on improving the docs 👍
